image:
  file: .gitpod.dockerfile

tasks:
  - init: ./init_tasks.sh && pip install -r requirements.txt
    command: python manage.py migrate
  - command: python manage.py runserver 0.0.0.0:8000


vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - ms-azuretools.vscode-docker
    - ms-toolsai.jupyter
    - ms-python.vscode-pylance
